name: Release Preparation

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: git settings
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name "github-ci"
          git remote set-url origin https://gatosyocora:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: copy & checkout to release branch
        run: |
          git branch release
          git switch release
          git merge master
      - name: copy readme & license
        run: |
          cp -f README.md ./Assets/VRCAvatars3Validator/README.md
          cp -f README.md.meta ./Assets/VRCAvatars3Validator/README.md.meta
          cp -f LICENSE ./Assets/VRCAvatars3Validator/LICENSE
          cp -f LICENSE.meta ./Assets/VRCAvatars3Validator/LICENSE.meta
      - name: git commit & push
        run: |
          git add .
          git commit -m "update files"
          git push origin release
          
          
